use_frameworks!

platform :ios, '8.0'

target 'MyUntity_Example' do
  pod 'MyUntity', :path => '../'
  pod 'YBBNetworking', :path => '../../YBBNetworking'

  target 'MyUntity_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
